version: "3.8"
services:
  nginx-trio-task:
    image: nginx:alpine
    build: nginx/
    ports:
      - target: 80
        published: 80
    networks:
      - trio-task-network
    volumes:
      - type: bind
        source: nginx/nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - flask-app
  flask-app:
    image: 1391819/trio-app:v2
    build: flask-app/ 
    networks:
      - trio-task-network
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mysql
  mysql:
    image: 1391819/trio-db:v1
    build: db/
    networks:
      - trio-task-network
    volumes:
      - type: volume
        source: trio-task-volume
        target: /var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
networks:
  trio-task-network:
volumes:
  trio-task-volume:
